version: 2
jobs:
  build:
    working_directory: ~/health_check_url
    docker:
      - image: golang:1.8
    steps:
      - checkout

      - run:
          name: Install Docker Client
          command: |
            echo "test"
            curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.6.tgz
            tar -xz -C /tmp -f /tmp/docker.tgz
            mv /tmp/docker/docker* /usr/bin/

            curl -L "https://github.com/docker/compose/releases/download/1.10.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
            chmod +x  /usr/bin/docker-compose

      - setup_docker_engine

      - run:
          name: Install aws-cli dependences.
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py 
            pip install awscli --upgrade

      - run:
          name: Get deploy script
          command: |
            aws configure set s3.signature_version s3v4
            aws s3 cp s3://citytaxi-credentials/healthcheckurl/healthcheckurl/deploy.sh deploy.sh
            chmod +x deploy.sh

      - run:
          name: deploy
          environment:
            AWS_DEFAULT_REGION: us-east-1
            REGISTRY: 433207076761.dkr.ecr.us-east-1.amazonaws.com
            IMAGE: dw_api
            STAGING_BRANCH: staging
            PRODUCTION_BRANCH: master
            DOCKER_TAG: "${CIRCLE_BUILD_NUM}"
            SERVICE: "healthcheckurl"
          command: |
            ./deploy.sh ci